baseURL = 'https://sindro.me/'
languageCode = 'en-us'
title = "Marcello Barnaba"
theme = "poison"

[pagination]
  pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  favicon = "/favicon.ico"
  brand = "sindro.me"
  brand_image = "/vjt.jpg"
  description = "feeling bold on the internet"
  blurb = "This is sindro.me, a weblog by Marcello Barnaba (@vjt) about technology, development, software, the internet, entertainment, politics, sociology, and the answer to Life, Universe, and Everything (42)."
  dark_mode = true
  noSummary = true
  foot_image = "/glider.png"
  foot_link = "http://catb.org/jargon"

  menu = [
    { Name = "About", URL = "/about/", HasChildren = false },
    { Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5 },
    { Name = "Links", URL = "" },
    { Name = "Privacy Policy", URL = "/privacy/", External = true },
    { Name = "Resume", URL = "/resume.pdf", External = true },
    { Name = "Segmentation fault (core dumped)", URL = "https://segmentation-fault.core-dumped.info/", External = true },
    { Name = "Wikipedia", URL = "https://en.wikipedia.org/wiki/User:Vjt", External = true },
    { Name = "Historical college projects", URL = "https://barnaba.openssl.it/", External = true },
    { Name = "Hacks - antifork (outdated)", URL = "https://antifork.org/", External = true },
  ]

  github_url = "https://github.com/vjt"
  linkedin_url = "https://linkedin.com/in/marcellobarnaba"
  twitter_url = "https://twitter.com/vjt"
  mastodon_url = "https://mastodon.social/@vjt"
  youtube_url = "https://youtube.com/user/vjti"
  instagram_url = "https://instagram.com/vjt42"
  facebook_url = "https://facebook.com/vjt.rb"
  flickr_url = "https://flickr.com/vjt-"
  telegram_url = "https://t.me/vjt42"
  email_url = "mailto:vjt@openssl.it"

  remark42 = true
  remark42_host = "https://remark.sindro.me"
  remark42_site_id = "remark.sindro.me"

[taxonomies]
  category = 'categories'
  series = 'series'
  tags = 'tags'
