baseURL = 'https://vjt.sindro.me/'
languageCode = 'en-us'
title = "Marcello Barnaba"
theme = "poison"
paginate = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  favicon = "/favicon.ico"
  brand = "sindro.me"
  brand_image = "/vjt.jpg"
  description = "feeling bold on the internet"
  dark_mode = true
  index_full_posts = true
  foot_image = "/glider.png"
  foot_link = "https://catb.org/jargon"

  menu = [
    { Name = "About", URL = "/about/", HasChildren = false },
    { Name = "Tags", URL = "/tags/" },
    { Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5 },
    { Name = "Links", URL = "" },
    { Name = "Resume", URL = "/resume.pdf", External = true },
    { Name = "Segmentation fault (core dumped)", URL = "https://segmentation-fault.core-dumped.info/", External = true },
    { Name = "Wikipedia", URL = "https://en.wikipedia.org/wiki/User:Vjt", External = true },
    { Name = "Historical college projects", URL = "https://barnaba.openssl.it/", External = true },
    { Name = "Hacks - antifork (outdated)", URL = "https://antifork.org/", External = true },
  ]

  github_url = "https://github.com/vjt"
  linkedin_url = "https://linkedin.com/in/marcellobarnaba"
  twitter_url = "https://twitter.com/vjt"
  youtube_url = "https://youtube.com/user/vjti"
  instagram_url = "https://instagram.com/vjt42"
  facebook_url = "https://facebook.com/vjt.rb"
  flickr_url = "https://flickr.com/vjt-"
  telegram_url = "https://t.me/vjt42"
  email_url = "mailto:vjt@openssl.it"

[taxonomies]
  series = 'series'
  tags = 'tags'
