baseURL = 'https://sindro.me/'
title = "Marcello Barnaba"
theme = "poison"
summaryLength = 250
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[pagination]
  pagerSize = 10

[markup.goldmark.renderer]
  unsafe = true

[params]
  favicon = "/favicon.ico"
  brand = "sindro.me"
  brand_image = "/vjt.jpg"
  og_image = "/sindrome.png"
  dark_mode = true
  foot_image = "/glider.png"
  foot_link = "http://catb.org/jargon"

  github_url = "https://github.com/vjt"
  linkedin_url = "https://linkedin.com/in/marcellobarnaba"
  twitter_url = "https://twitter.com/vjt"
  mastodon_url = "https://mastodon.social/@vjt"
  youtube_url = "https://youtube.com/user/vjti"
  instagram_url = "https://instagram.com/vjt42"
  facebook_url = "https://facebook.com/vjt.rb"
  flickr_url = "https://flickr.com/vjt-"
  telegram_url = "https://t.me/vjt42"
  email_url = "mailto:vjt@openssl.it"

  remark42 = true
  remark42_host = "https://remark.sindro.me"
  remark42_site_id = "remark.sindro.me"

[taxonomies]
  category = 'categories'
  tags = 'tags'

[languages]
  [languages.en]
    languageCode = 'en-us'
    languageName = 'English'
    weight = 1
    [languages.en.params]
      description = "feeling bold on the internet"
      blurb = "This is sindro.me, a weblog by Marcello Barnaba (@vjt) about technology, development, software, the internet, entertainment, politics, sociology, and the answer to Life, Universe, and Everything (42)."
      menu = [
        { Name = "About", URL = "/about/", HasChildren = false },
        { Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5 },
        { Name = "Links", URL = "" },
        { Name = "Privacy Policy", URL = "/privacy/", External = true },
        { Name = "Resume", URL = "/resume.pdf", External = true },
        { Name = "Segmentation fault (core dumped)", URL = "https://segmentation-fault.core-dumped.info/", External = true },
        { Name = "Wikipedia", URL = "https://en.wikipedia.org/wiki/User:Vjt", External = true },
        { Name = "Historical college projects", URL = "https://barnaba.openssl.it/", External = true },
        { Name = "Hacks - antifork (outdated)", URL = "https://antifork.org/", External = true },
      ]

  [languages.it]
    languageCode = 'it'
    languageName = 'Italiano'
    weight = 2
    [languages.it.params]
      description = "audace su internet"
      blurb = "Questo è sindro.me, un blog di Marcello Barnaba (@vjt) su tecnologia, sviluppo, software, internet, intrattenimento, politica, sociologia e la risposta alla Vita, all'Universo e a Tutto Quanto (42)."
      menu = [
        { Name = "Chi sono", URL = "/it/about/", HasChildren = false },
        { Name = "Articoli", URL = "/it/posts/", Pre = "Recenti", HasChildren = true, Limit = 5 },
        { Name = "Link", URL = "" },
        { Name = "Privacy", URL = "/it/privacy/", External = true },
        { Name = "Curriculum", URL = "/resume.pdf", External = true },
        { Name = "Segmentation fault (core dumped)", URL = "https://segmentation-fault.core-dumped.info/", External = true },
        { Name = "Wikipedia", URL = "https://it.wikipedia.org/wiki/Utente:Vjt", External = true },
        { Name = "Progetti universitari", URL = "https://barnaba.openssl.it/", External = true },
        { Name = "Hacks - antifork (datato)", URL = "https://antifork.org/", External = true },
      ]
